Test_BP/urls.py
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from Test_BP import settings
from core import urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from core import views
from core.views import InfoView, get_request_data, get_info_request, profile_view, related_view, requests_view, signup, \
    message_view, client_message, new_message

urlpatterns = [
    # path('index', views.index),
    path('', views.InfoView, name='InfoView'),
    path('', include('django.contrib.auth.urls')),
    path('faq', views.faq, name='faq'),
    path('ziadost/info', get_request_data, name='ziadost_info'),
    # path('get_prisoner_values', views.get_prisoner_values, name='get_prisoner_values'),
    path('ziadost/info_logged_in', get_info_request, name='ziadost_info_logged_in'),
    path('ziadost/bankove_spojenie', views.money, name='money'),
    path('ziadost/navsteva', views.visit, name='visit'),
    path('ziadost/detail=<int:req_id>', views.info_detail, name='info_detail'),
    path('profil', profile_view, name='profile'),
    path('profil/pribuzny', related_view, name='related'),
    path('profil/ziadosti', requests_view, name='requests'),
    path('register', signup, name='register'),
    path('profil/spravy', message_view, name='messages_page'),
    path('profil/spravy/<int:id>/', client_message, name='messages'),
    path('profil/spravy/nova_sprava/', new_message, name='new_message'),
    path('load-more', views.load_more, name='load_more'),
    path('load-users', views.load_users, name='load_users'),
    path('ustavy/', views.departments, name='departments'),
    path('podpora/', views.support, name='support'),
    path('forum/', views.forum_view, name='forum_view'),
    path('forum/kategoria/<int:category_id>', views.category_view, name='category_view'),
    path('forum/prispevok/<int:post_id>', views.post_view, name='post_view'),
    path('forum/send_comment', views.send_forum_post, name='send_forum_post'),
    path('forum/delete_comment', views.delete_comment, name='delete_comment'),
    path('forum/editovat_prispevok/<int:post_id>', views.edit_post, name='edit_post'),
    path('forum/editovat_komentar/<int:post_id>', views.edit_comment, name='edit_comment'),
    path('forum/edit_comment_back', views.edit_comment_back, name='edit_comment_back'),
    path('forum/edit_comment_back2', views.edit_comment_back2, name='edit_comment_back2'),
    path('forum/novy_prispevok/', views.new_post, name='new_post')
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
import datetime
from datetime import timezone

from django.contrib.auth.models import AbstractUser
from django.db import models
from django_quill.fields import QuillField

from Test_BP import settings


class Cities(models.Model):
    municipalityCode = models.TextField()
    municipalityName = models.TextField()
    countyIdentifier = models.IntegerField()
    status = models.TextField()

    def __str__(self):
        return self.municipalityName


class User(AbstractUser):
    SEX_CHOICES = (
        ('F', 'Zena',),
        ('M', 'Muz',),
        ('O', 'Ine',),
    )

    sex = models.CharField(
        max_length=1,
        choices=SEX_CHOICES,
        null=False,
        default='M'
    )
    city = models.ForeignKey(Cities, on_delete=models.CASCADE, null=True)
    street = models.TextField(null=False)
    date_of_birth = models.DateField(blank=False, default=datetime.date.today)

    class Meta:
        verbose_name_plural = 'Uzivatelia'

    def __str__(self):
        return self.first_name + " " + self.last_name + " | " + str(self.date_of_birth) + " | " + self.username


class Department(models.Model):
    name = models.CharField(blank=False, max_length=255)
    type = models.CharField(max_length=1024, blank=True)
    lat = models.CharField(max_length=18, blank=True)
    long = models.CharField(max_length=18, blank=True)
    address = models.TextField(blank=True)
    phone = models.TextField(blank=True)
    email = models.TextField(blank=True)
    web = models.TextField(blank=True)
    iban = models.CharField(max_length=24, blank=True)
    acc_name = models.TextField(blank=True)
    acc_adr = models.TextField(blank=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Ústav',
        verbose_name_plural = 'Ústavy'


class Questions(models.Model):
    question = models.TextField()
    answer = models.TextField()

    class Meta:
        verbose_name = 'Najcastesia otazka'
        verbose_name_plural = 'Najcastesie otazky'

    def __str__(self):
        return self.question


class Prisoner(models.Model):
    first_name = models.TextField(max_length=255, blank=False)
    last_name = models.TextField(max_length=255, blank=False)
    date_of_birth = models.DateField(blank=False)
    prisoner_num = models.TextField(max_length=255, blank=False)
    department = models.ForeignKey(Department, on_delete=models.CASCADE, verbose_name='ustav')

    def __str__(self):
        return self.prisoner_num + " | " + self.first_name + " " + self.last_name

    class Meta:
        verbose_name = 'Väzen'
        verbose_name_plural = 'Väzni'


class MatchPrisoner(models.Model):
    user_id = models.ForeignKey(User, on_delete=models.CASCADE)
    prisoner_id = models.ForeignKey(Prisoner, on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'Priradenie vazna'
        verbose_name_plural = 'Priradenie vaznov'

    def __str__(self):
        return self.user_id.first_name + " " + self.user_id.last_name + " + " + self.prisoner_id.first_name + " " + \
               self.prisoner_id.last_name + " - ID:" + self.prisoner_id.prisoner_num


class Message(models.Model):
    sender = models.ForeignKey(User, on_delete=models.CASCADE, related_name='sender')
    receiver = models.ForeignKey(User, on_delete=models.CASCADE, related_name='receiver')
    date = models.DateTimeField(auto_now=True)
    viewed = models.BooleanField(default=False)
    text = models.TextField(blank=False, null=False)


class Page(models.Model):
    title = models.TextField(null=False, default="Nova stranka")
    content = QuillField()
    show = models.BooleanField(default=False)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Stranka'
        verbose_name_plural = 'Stranky'


class GroupPage(models.Model):
    title = models.TextField(null=None, default="Nova skupina stranok")
    info = models.TextField(null=None)

    class Meta:
        verbose_name = 'Skupina stranok'
        verbose_name_plural = 'Skupiny stranok'

    def __str__(self):
        return self.title


class MatchPages(models.Model):
    page = models.ForeignKey(Page, on_delete=models.CASCADE, related_name='page')
    group = models.ForeignKey(GroupPage, on_delete=models.CASCADE, related_name='group')

    class Meta:
        verbose_name = 'Priradenie do skupin'
        verbose_name_plural = 'Priradenie stranok do skupin'

    def __str__(self):
        return self.group.title + ' | ' + self.page.title


class ForumCategory(models.Model):
    title = models.TextField(max_length=255, blank=False)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Kategória fóra'
        verbose_name_plural = 'Kategórie fóra'


class ForumPost(models.Model):
    title = models.TextField(max_length=1024, blank=False, null=False)
    category = models.ForeignKey(ForumCategory, on_delete=models.CASCADE, related_name='category')
    creator = models.ForeignKey(User, on_delete=models.CASCADE, related_name='post_user')
    created_at = models.DateTimeField(auto_now_add=True)
    edited_at = models.DateTimeField(auto_now=True)
    text = QuillField()

    class Meta:
        verbose_name = 'Otázka vo fóre'
        verbose_name_plural = 'Otázky fo fóre'

    def __str__(self):
        return self.title


class ForumComment(models.Model):
    creator = models.ForeignKey(User, on_delete=models.CASCADE, related_name='comment_user')
    created_at = models.DateTimeField(auto_now=False)
    edited_at = models.DateTimeField(auto_now=True)
    text = QuillField()

    def __str__(self):
        return self.creator.first_name + " " + self.creator.last_name + " " + self.created_at.strftime("%d-%m-%Y %H:%M")

    class Meta:
        verbose_name = 'Komentár k príspevku vo fóre'
        verbose_name_plural = 'Komentáre vo fóre'


class MatchForumComment(models.Model):
    forum_post = models.ForeignKey(ForumPost, on_delete=models.CASCADE, related_name='post')
    forum_comment = models.ForeignKey(ForumComment, on_delete=models.CASCADE, related_name='comment')

    class Meta:
        verbose_name = 'Priradenie komentáru k príspevku vo fóre'
        verbose_name_plural = 'Priradenie komentárov k príspevkom'

    def __str__(self):
        return self.forum_post.title + " + " + self.forum_comment.creator.first_name + " " + \
               self.forum_comment.creator.last_name + " " + self.forum_comment.created_at.strftime("%d-%m-%Y %H:%M")


class News(models.Model):
    title = models.TextField(max_length=1024, blank=False, null=False)
    text = models.TextField()
    visible = models.BooleanField(default=True)
    img = models.ImageField(upload_to='img/uploaded/', blank=True)

    class Meta:
        verbose_name = 'Prezentačný slajd'
        verbose_name_plural = 'Prezentačné slajdy'

    def __str__(self):
        return self.title


class Requests(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE,verbose_name='Používateľ')
    prisoner = models.ForeignKey(Prisoner, on_delete=models.CASCADE, verbose_name='Väzeň')
    reason = models.TextField(verbose_name='Odôvodnenie')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Vytvorené')
    edited_at = models.DateTimeField(auto_now=True, verbose_name='Upravené',)
    answer = models.TextField(blank=True, verbose_name='Odpoveď')

    Types = (
        ('N', 'Žiadosť o návštevu',),
        ('T', 'Žiadosť o telefonát',),
        ('V', 'Žiadosť o videohovor',),
    )

    States = (
        ('R', 'Rieši sa',),
        ('S', 'Schválená',),
        ('F', 'Zamietnutá',),
        ('P', 'Poslaná',),
    )

    type = models.CharField(
        max_length=1,
        choices=Types,
        null=False,
        default='N',
        verbose_name='Typ'
    )

    state = models.CharField(
        max_length=1,
        choices=States,
        null=False,
        default='P',
        verbose_name='Status'
    )

    class Meta:
        verbose_name_plural = 'Žiadosti'

    def get_type_name(self):
        if self.type == 'V':
            return "Žiadosť o videohovor"
        elif self.type == 'T':
            return "Žiadosť o telefonát"
        else:
            return "Žiadosť o návštevu"

    def __str__(self):
        return self.user.first_name + " " + self.user.last_name + " | " + self.prisoner.prisoner_num + " | " + \
               self.get_type_name()


class RequestsInfo(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Používateľ')
    reason = models.TextField(verbose_name='Odôvodnenie')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Vytvorené')
    edited_at = models.DateTimeField(auto_now=True, verbose_name='Upravené',)
    answer = models.TextField(blank=True, verbose_name='Odpoveď')

    States = (
        ('R', 'Rieši sa',),
        ('S', 'Schválená',),
        ('F', 'Zamietnutá',),
        ('P', 'Poslaná',),
    )

    state = models.CharField(
        max_length=1,
        choices=States,
        null=False,
        default='P',
        verbose_name='Status'
    )

    class Meta:
        verbose_name_plural = 'Žiadosti o pridelenie informácií o väzňovi'

    def __str__(self):
        return self.user.first_name + " " + self.user.last_name

templates/base.html
{% extends 'index.html' %}
{% block css %}{% endblock css %}
{% block content %}{% endblock content %}
{% block extra_js %}{% endblock extra_js %}

templates/carousel.html
{% load static %}

<div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="carousel">
  <ol class="carousel-indicators">
      {% for new in news %}
          <li data-bs-target="#carouselExampleIndicators" data-bs-slide-to="{{ forloop.counter0 }}"
              {% if forloop.first %}class="active"{% endif %}></li>
      {% endfor %}
  </ol>
  <div class="carousel-inner">
      {% for new in news %}
        <div class="carousel-item {% if forloop.first %}active{% endif %}">
          <div class="container-t">
            <img src="{% get_media_prefix %}{{ new.img }}" class="d-block w-100 img-fluid" alt="{{ new.title }}">
            <div class="carousel-caption d-none d-md-block">
              <h5>{{ new.title }}</h5>
              <p>{{ new.text|safe }}</p>
            </div>
          </div>
        </div>
      {% endfor %}


  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Predchádzajúca</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Ďalšia</span>
  </a>
</div>

templates/departments.html
{% extends 'index.html' %}
{% block title %}Zoznam ústavov{% endblock %}
{% block content %}
    <div class="container mt-3">
        <h1>Zoznam ústavov</h1>
    <div class="row justify-content-between">
        {% for department in data %}
        <div class="card border-0 my-3 mx-auto col-xl-6 col-md-6 col-12 ">
          <div class="card-body shadow px-4 py-4">
            <h4 class="card-title">{{ department.name }}</h4>
            <h6 class="card-subtitle mb-2 text-muted">{{ department.type }}</h6>
            <p class="card-text"><b>Adresa:</b><br/>{{ department.address }}</p>
              <span>
                  Email: <a href="mailto:{{ department.email }}" class="link-dark">{{ department.email }}</a>
              </span><br/>
              <span>
                  Telefón: <a href="tel:{{ department.phone }}" class="link-dark">{{ department.phone }}</a>
              </span><br/>
              <span>
                  Web: <a href="{{ department.web }}" class="card-link">{{ department.web }}</a>
              </span>
              <div class="mt-3">
                  <span>Bankové spojenie:<br/></span>
                  <span>
                      <b>IBAN:</b> {{ department.iban }}<br/>
                      <b>Názov účtu ústavu:</b> {{ department.acc_name }}<br/>
                      <b>Korešpondenčná adresa ústavu:</b> {{ department.acc_adr }}
                  </span>
              </div>
          </div>
        </div>
    {% endfor %}
    </div>
    </div>

{% endblock %}

templates/faq.html
{% extends 'index.html' %}
{% block title %}FAQ - Najcastejsie otazky{% endblock %}

{% block content %}
    <div class="container mt-5">
    {% if not questions %}
        <h1>Ziadne najcastejsie otazky</h1>
    {% else %}
        <h1>Najcastejsie otazky</h1>
         <div class="accordion" id="accordionExample">
        {% for question in questions %}
          <div class="accordion-item">
            <h2 class="accordion-header" id="headingOne">
              <button class="accordion-button {% if not forloop.first %}collapsed {% endif %}" type="button" data-bs-toggle="collapse" data-bs-target="#collapse{{ question.id }}" aria-expanded="true" aria-controls="collapseOne">
                  <strong>{{ question.question }}</strong>
              </button>
            </h2>
            <div id="collapse{{ question.id }}" class="accordion-collapse collapse {% if forloop.first %}show{% endif %}" aria-labelledby="headingOne" data-bs-parent="#accordionExample">
              <div class="accordion-body">
                {{ question.answer }}
              </div>
            </div>
          </div>
        {% endfor %}
        </div>
    {% endif %}

    </div>


{% endblock %}

templates/header.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark" aria-label="Ninth navbar example">
    <div class="container-xl">
        <a class="navbar-brand" href="{% url 'InfoView' %}">Názov aplikácie</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarsExample07XL" aria-controls="navbarsExample07XL" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarsExample07XL">
{#            <form class="ms-auto">#}
{#                <input class="form-control" type="text" placeholder="Hľadať" aria-label="Search">#}
{#            </form>#}
            <ul class="ms-auto navbar-nav me-3  mb-2 mb-lg-0">
                <li class="nav-item active">
                    <a class="nav-link" aria-current="page" href="{% url 'departments' %}">Ústavy</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'support' %}">Podpora</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href='{% url 'faq' %}'>FAQ</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="dropdown07XL" data-bs-toggle="dropdown" aria-expanded="false">Žiadosti</a>
                    <ul class="dropdown-menu" aria-labelledby="dropdown07XL">
                        <li><a class="dropdown-item" href="{% url 'ziadost_info' %}">Žiadosť o pridelenie informácií</a></li>
                        <li><a class="dropdown-item" href="{% url 'visit' %}">Žiadosť o telefonát, videohovor, návštevu</a></li>
                        <li><a class="dropdown-item" href="{% url 'money' %}">Peňažné prostriedky pre väzňa</a></li>
                    </ul>
                </li>
                {% block content %}
                {% if user.is_authenticated %}
                    <li class="ms-lg-3">
                        <a class="nav-link" href="{% url 'forum_view' %}">Fórum</a>
                    </li>
                    <li class="ms-lg-3">
                        <a class="nav-link" href="{% url 'profile' %}">{{ user.username }}</a>
                    </li>
                    <li>
                        <a class="nav-link" href="{% url 'logout' %}">Odhlasit sa</a>
                    </li>
                {% else %}
                    <li>
                        <a class="nav-link" href="{% url 'register' %}">Registrovat sa</a>
                    </li>
                    <li>
                        <a class="nav-link" href="{% url 'login' %}">Prihlasit sa</a>
                    </li>
                {% endif %}
                {% endblock %}
            </ul>
        </div>
    </div>
</nav>

templates/home.html
{% extends 'index.html' %}

{% block title %}Domov{% endblock %}

{% block content %}
{% include 'carousel.html' %}
    <div class="container mt-5">
        <h1>Motto webu</h1>
        <h4>Nejaky dalsi popis ak bude treba</h4>
    </div>

{% endblock %}

templates/index.html
{% load static %}

<!doctype html>
<html lang="sk">
<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- Bootstrap CSS -->
  <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'css/style.css' %}" rel="stylesheet">

<script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
  <link href="https://cdn.quilljs.com/1.1.6/quill.snow.css" rel="stylesheet">
  <script src="https://cdn.quilljs.com/1.1.6/quill.js"></script>

  <title>{% block title %}Nazov aplikacie{% endblock %}</title>
</head>
<body>

{% include 'header.html' %}

{% block content %}
{% endblock %}

<!-- Option 1: Bootstrap Bundle with Popper -->
<script src="{% static 'js/bootstrap.bundle.js' %}"></script>

<!-- Option 2: Separate Popper and Bootstrap JS -->
<!--
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js" integrity="sha384-q2kxQ16AaE6UbzuKqyBE9/u/KzioAlnx2maXQHiDX9d4/zp8Ok3f+M7DPm+Ib6IU" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-pQQkAEnwaBkjpqZ8RU1fF1AKtTcHJwFl3pblpTlHXybJjHpMYo79HY3hIi4NKxyj" crossorigin="anonymous"></script>
-->

<link rel="stylesheet" href="http://code.jquery.com/ui/1.11.0/themes/smoothness/jquery-ui.css">
<script src="http://code.jquery.com/jquery-1.9.1.js"></script>
<script src="http://code.jquery.com/ui/1.11.0/jquery-ui.js"></script>
<link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>



{% block extra_js %}

{% endblock extra_js %}

<script>
    $(document).ready(function (){
        $("#loader").on('click', function (){
            var currentResult = $(".msg_sent").length;
            $.ajax({
                url: "{% url 'load_more' %}",
                type: 'post',
                data: {
                    csrfmiddlewaretoken: "{{ csrf_token }}",
                    'offset': currentResult,
                    'id': "{{ contact.id }}",
                },
                dataType:'json',
                beforeSend:function (){
                    $("#loader").addClass('disabled').text('Nacitavam...');
                },
                success:function (res){
                    var _html= $(".post-box").html();
                    var json_data=$.parseJSON(res.posts);
                    $.each(json_data, function (index, data) {
                        if (data.received) {
                            _html = '<div class="msg_sent col-xl-7 col-md-10 me-auto my-1 alert-secondary p-3"> \
                <div class="row"> \
                    <div class="col"> \
                        <h6>' + data.username + '</h6> \
                    </div> \
                    <div class="col"> \
                        <span class="float-end">' + data.date + '<span> \
                    </div> \
                </div> \
                <div class=""> \
                    <span>' + data.text + '</span>\
                </div> \
            </div>' + _html
                        } else {
                            _html = '<div class="msg_sent col-xl-7 col-md-10 col-12 ms-auto my-1 alert-primary p-3"> \
                <div class="row"> \
                    <div class="col"> \
                        <h6>'+ data.username + '</h6> \
                    </div> \
                    <div class="col"> \
                        <span class="float-end">' + data.date + '</span> \
                    </div> \
                </div> \
                <div class=""> \
                    <span>' + data.text + '</span> \
                </div> \
            </div> ' + _html
                        }

                    });
                    $('.post-box').html(_html);
                    var count = $(".msg_sent").length;
                    console.log(count, res.totalResults)
                    if (count == res.totalResults) {
                        $("#loader").remove();
                    } else {
                        $("#loader").removeClass('disabled').text('Nacitaj dalsie');
                        console.log(res);
                    }
                }
            })
        });
    });
</script>

<script>
    $(document).ready(function () {
       {#$('#selector_name').select2();#}
       {#var value = $(".select2-search__field").val();#}


       $('#selector_name').select2({
          ajax: {
            url: '{% url 'load_users' %}',
            dataType: "json",
            type: "GET",
            processResults: function (data) {
                return {
                    results: $.map(data, function (item) {
                        return {id: item.id, text: item.username + " | " + item.first_name + " " + item.last_name}
                    }),
                    page: data.page || 1
                }
            },
            cache: true,


            // Additional AJAX parameters go here; see the end of this chapter for the full code of this example
          },
          placeholder: 'Zadajte prezyvku, meno a priezvisko pouzivatela',
            minimumInputLength: 1,
          language: {
            inputTooShort: function () {
            return "Zacnite pisat";
            }
            }
        });
    });
</script>

{% block scripts %}
{% endblock %}

{{ form.media }}

<!-- Include the Quill library -->
<script src="https://cdn.quilljs.com/1.3.6/quill.js"></script>

<!-- Initialize Quill editor -->
<script>
  var quill = new Quill('#editor', {
    theme: 'snow'
  });
</script>


</body>
</html>

templates/online_ziadost.html
{% extends 'index.html' %}
{% block title %}Ziadost o pridelenie informacii{% endblock %}

{% block content %}
<div class="mt-5 container">
    <h1>Žiadosť o povolenie informacii</h1>
    <p>popis žiadosti o povolenie informácia - možné doplniť ak bude treba</p>
    {% if form  %}
    <h3 class="mb-3">Doplnenie údajov do žiadosti</h3>
    <form method="post">
    {% csrf_token %}
        <div class="mb-3">
            <label for="{{ form.text.id_for_label }}" class="form-label">Text žiadosti (vec, meno väzňa, údaje o
                väzňovi (pre overenie), odôvodnenie):</label>
            <textarea type="text" id="{{ form.text.id_for_label }}" class="form-control" name="{{ form.text.html_name }}"></textarea>
        </div>

        <button type="submit" class="btn btn-primary mt-3 mb-3">Odoslat online ziadost</button>

        {% if form.errors %}
            <div class="alert alert-danger" role="alert">
              <h4 class="alert-heading">Nepodarilo sa doplnit ziadost!</h4>
              <hr>
                <p class="mb-0">
                    Udaje, ktore ste doplnili nie su spravne.
                </p>
            </div>

        {% endif %}
    </form>

    {% else %}
        <div class="alert alert-success" role="alert">
              <h4 class="alert-heading">Ziadost bola uspesne odoslana!</h4>
              <hr>
                <p class="mb-0">
                    O jej schvaleni, respektive zamietnuti vas budeme informovat.
                </p>
            </div>
    {% endif %}
</div>

    <link rel="stylesheet" href="http://code.jquery.com/ui/1.11.0/themes/smoothness/jquery-ui.css">
<script src="http://code.jquery.com/jquery-1.9.1.js"></script>
<script src="http://code.jquery.com/ui/1.11.0/jquery-ui.js"></script>
<script>
$(document).ready(function() {
    $('.datepicker').datepicker();
});
</script>
{% endblock %}

templates/related.html
{% extends 'profile.html' %}
{% block title %}Profil - pribuzny{% endblock %}
{% block profile_content %}
    {% if not related %}
        <h3>Momentalne nemate informacie o ziadnom pribuznom!</h3>
        <a href="{% url 'ziadost_info' %}">Poziadat o informacie o mojom pribuznom</a>
    {% else %}
        <h3>Tu sa zobrazia vysledky</h3>
    {% endif %}
{% endblock %}

templates/request_detail.html
{% extends 'index.html' %}
{% load static %}
{% block title %}#{{ request.id }} {{ request.get_type_name }}{% endblock %}
{% block content %}
<div class="mt-5 container alert alert-{% if request.state == 'P' %}secondary{% elif request.state == 'R'%}primary
                        {% elif request.state == 'S'%}success{% else %}danger{% endif %}">

    <h1 class="mb-3">#{{ request.id }} {{ request.get_type_name }}</h1>
    <div class="mb-3 row">
        <div class="col-lg-2">
            <span>Žiadateľ:</span>
        </div>
        <div class="col-lg-10">
            <h6>{{ request.user.first_name }} {{ request.user.last_name }}</h6>
        </div>

        <div class="col-lg-2">
            <span>Príbuzný väzeň:</span>
        </div>
        <div class="col-10">
            <h6>{{ request.prisoner.first_name }} {{ request.prisoner.last_name }} | {{ request.prisoner.prisoner_num }}</h6>
        </div>

        <div class="col-lg-2">
            <span>Odôvodnenie:</span>
        </div>
        <div class="col-10">
            <h6>{{ request.reason }}</h6>
        </div>

        <div class="col-lg-2">
            <span>Odpoveď:</span>
        </div>
        <div class="col-10">
            <h6>{{ request.answer }}</h6>
        </div>

        <div class="col-lg-2">
            <span>Stav:</span>
        </div>
        <div class="col-10">
            <h6>{{ request.get_state_display }}</h6>
        </div>
    </div>

</div>



{% endblock %}